In [5]:
import numpy as np

array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(array1[-1,:])

[ 6  7  8  9 10]

In [9]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a=array.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
array1 = np.array([[1,2],[3,4]])

array2 = np.array([[-1,-2],[-3,-4]])

np.hstack((array1,array2))

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [17]:
a = np.array([1,2,3])

print(a.sum()) 

print(a.max()) 

print(a.min())

6
3
1

In [19]:
np.linspace(10,15,5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [21]:
dictionary = {"NAME":["ali","veli","kenan","hilal","ayse","evren"],

              "AGE":[15,16,17,33,45,66],

              "MAAS": [100,150,240,350,110,220]}

dataFrame1 = pd.DataFrame(dictionary)

dataFrame1[dataFrame1.AGE > 60]

    NAME  AGE  MAAS
5  evren   66   220

In [23]:
dictionary = {"NAME":["ali","veli","kenan","hilal","ayse","evren"],

              "AGE":[15,16,17,33,45,66],

              "MAAS": [100,150,240,350,110,220]}

dataFrame1 = pd.DataFrame(dictionary)

ortalama_maas = dataFrame1.MAAS.mean()

s = np.sum([True if ortalama_maas > each else False for each in dataFrame1.MAAS])
s

3

In [3]:

import pandas as pd
dictionary = {"NAME":["ali","veli","kenan","hilal","ayse","evren"],

              "AGE":[15,16,17,33,45,66],

              "MAAS": [100,150,240,350,110,220]}

dataFrame1 = pd.DataFrame(dictionary)
dataFrame1.describe()

             AGE        MAAS
count   6.000000    6.000000
mean   32.000000  195.000000
std    20.474374   94.815611
min    15.000000  100.000000
25%    16.250000  120.000000
50%    25.000000  185.000000
75%    42.000000  235.000000
max    66.000000  350.000000

In [27]:
dictionary = {"NAME":["ali","veli","kenan","hilal","ayse","evren"],

              "AGE":[15,16,17,33,45,66],

              "MAAS": [100,150,240,350,110,220]}

dataFrame1 = pd.DataFrame(dictionary)

pd.concat([dataFrame1["NAME"],dataFrame1["MAAS"]],axis=0)

0      ali
1     veli
2    kenan
3    hilal
4     ayse
5    evren
0      100
1      150
2      240
3      350
4      110
5      220
dtype: object

In [29]:
dictionary = {"NAME":["ali","veli","kenan","hilal","ayse","evren"],

              "AGE":[15,16,17,33,45,66],

              "MAAS": [100,150,240,350,110,220]}

dataFrame1 = pd.DataFrame(dictionary)

dataFrame1.iloc[:,2]

0    100
1    150
2    240
3    350
4    110
5    220
Name: MAAS, dtype: int64

In [31]:
import pandas as pd

dictionary = {"NAME":["ali","veli","kenan","hilal","ayse","evren"],

              "AGE":[15,16,17,33,45,66],

              "MAAS": [100,150,240,350,110,220]}

dataFrame1 = pd.DataFrame(dictionary)

[ each*2 for each in dataFrame1.AGE]

[30, 32, 34, 66, 90, 132]